<?php

namespace Schema\Engine;

class Product extends BaseEngine {

//    public $productData;


    public function __construct() {
    }

    public static function register() {

    }

////
//    public function schema() {
//        return parent::schema( $templatePath  ); // TODO: Change the autogenerated stub
//    }
//
//    protected function name() {
//
//    }
//

//    function test() {
//
//        if ( is_a( $this->productData, 'WC_Product' ) ) {
//            echo 'Product ID: ' . $this->productData->get_id();
//        } else {
//            echo 'Product data is not set or not a valid WC_Product object.';
//        }
//    }
//}


//class Product {
//
//    public $productData;
//
//    public function __construct() {
//        $this->productData = global $product;
//    }
//
//    function test(){
//        echo 'nymul-islam' . $this->productData->get_id();
//
////        if ( is_a( $product, 'WC_Product' ) ) {
////            $product_id = $product->get_id();
////            echo 'The current product ID is: ' . $product_id;
////        } else {
////            echo 'Not a product page.';
////        }
////        echo 'from-product';
//    }
}